mod ownership;
mod vars_and_arrays;
mod slices;
mod structs;
mod dfs;
mod enums_and_option;
mod bfs_min_distance;
mod merge_sort;
mod collections;
mod strings;
mod errors;
mod generics;
mod traits;
mod lifetimes;
fn main() {
    // vars_and_arrays::test();
    // ownership::test();
    // slices::test();
    // structs::test();
    // dfs::main();
    // bfs_min_distance::main();
    // merge_sort::main();
    // enums_and_option::test();
    // collections::main();
    // strings::main();
    // errors::main();
    // generics::main();
    // traits::main();
    lifetimes::main();
}